"""Framework-neutral capture and replay primitives for temporal tools."""

from .clock import VirtualClock, format_timestamp, parse_timestamp
from .evaluation import (
    FactualClaim,
    PairedScenarioResult,
    RepeatedArmMetrics,
    RepeatedPairedScenarioResult,
    ResearchTrace,
    ScenarioRubric,
    TraceMetrics,
    cited_claims_from_markdown,
    compare_pair,
    compare_recorded_runs,
    decision_stability,
    run_paired_evaluation,
    run_repeated_paired_evaluation,
    score_recorded_run,
    score_trace,
    trace_from_tool_run,
)
from .gateway import ReplayedToolError, ReplayMissError, ReplayTapeMismatchError, TemporalGateway
from .importers import ImportSummary, import_archive_jsonl
from .models import (
    EvidenceRecord,
    LLMCallRecord,
    ScenarioDefinition,
    ScenarioRubricRecord,
    ScenarioSnapshot,
    SearchManifest,
    SearchTraceRecord,
    TemporalMode,
    TemporalOutcome,
    TemporalSearchResponse,
    TemporalSearchResult,
    ToolTraceRecord,
    canonical_json,
    request_key,
)
from .runtime import TemporalContext, current_context, temporal_context
from .search import TemporalSearch
from .simulation import (
    Fill,
    InsufficientBuyingPowerError,
    MarketQuote,
    MarketTimingError,
    Order,
    OrderSide,
    PortfolioSimulator,
    PortfolioState,
)
from .store import TemporalStore

__all__ = [
    "EvidenceRecord",
    "FactualClaim",
    "Fill",
    "ImportSummary",
    "InsufficientBuyingPowerError",
    "LLMCallRecord",
    "MarketQuote",
    "MarketTimingError",
    "Order",
    "OrderSide",
    "PairedScenarioResult",
    "PortfolioSimulator",
    "PortfolioState",
    "ReplayMissError",
    "ReplayTapeMismatchError",
    "RepeatedArmMetrics",
    "RepeatedPairedScenarioResult",
    "ResearchTrace",
    "ScenarioRubric",
    "ScenarioRubricRecord",
    "ReplayedToolError",
    "TemporalContext",
    "TemporalGateway",
    "TemporalMode",
    "TemporalOutcome",
    "TemporalSearch",
    "TemporalSearchResponse",
    "TemporalSearchResult",
    "ToolTraceRecord",
    "TemporalStore",
    "TraceMetrics",
    "VirtualClock",
    "canonical_json",
    "cited_claims_from_markdown",
    "compare_pair",
    "compare_recorded_runs",
    "current_context",
    "decision_stability",
    "format_timestamp",
    "import_archive_jsonl",
    "parse_timestamp",
    "request_key",
    "run_paired_evaluation",
    "run_repeated_paired_evaluation",
    "score_trace",
    "score_recorded_run",
    "SearchManifest",
    "SearchTraceRecord",
    "ScenarioSnapshot",
    "ScenarioDefinition",
    "temporal_context",
    "trace_from_tool_run",
]
